In [1]:
# For testing aspects of kmeans
import numpy as np
from kmeans import Cluster

In [2]:
np.random.randint(0, 10, size=10)

array([1, 2, 1, 8, 9, 1, 2, 8, 0, 9])

In [11]:
# Deleting even items
lst = list(np.arange(0, 10))
print(lst)
for ix, item in enumerate(lst):
    if item % 2 == 0:
        print('DELETE:', item)
        # lst.remove(item)
        del lst[ix]

print(lst)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
DELETE: 0
DELETE: 2
DELETE: 4
DELETE: 6
DELETE: 8
[1, 3, 5, 7, 9]


In [2]:
samples = 10
features = 5
x = []
for i in range(samples):
    x.append(np.random.normal(size=(features, )))

centroid = np.mean(x, axis=0)
print(centroid.shape)

(5,)


In [6]:
x1 = np.arange(0, 9)
x2 = np.arange(1, 10)

c1 = Cluster(centroid=x1)
c2 = Cluster(centroid=x2)

print('Inspect Cluster:')
print(c1)

print('Check equality:')
print(c1 == c2)

print('Inspect vectors:')
print(x1)
print(x2)

Inspect Cluster:
<class 'kmeans.Cluster'> object at 0x29fec626dc0: (centroid=[0 1 2 3 4 5 6 7 8], label=None)
Check equality:
False
Inspect vectors:
[0 1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 9]


In [4]:
# Subtraction operation
print(c1 - c2)
print(c2 - c1)
print(c1 - x1)
print(c2 - x1)

[-1 -1 -1 -1 -1 -1 -1 -1 -1]
[1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1]
