In [1]:
# For testing aspects of kmeans
import numpy as np
from kmeans import Cluster

In [2]:
samples = 10
features = 5
x = []
for i in range(samples):
    x.append(np.random.normal(size=(features, )))

centroid = np.mean(x, axis=0)
print(centroid.shape)

(5,)


In [3]:
x1 = np.arange(0, 9)
x2 = np.arange(1, 10)

c1 = Cluster(centroid=x1)
c2 = Cluster(centroid=x2)

print('Inspect Cluster:')
print(c1)

print('Inspect vectors:')
print(x1)
print(x2)

Inspect Cluster:
<class 'kmeans.Cluster'> object at 0x29968334940: (centroid=[0 1 2 3 4 5 6 7 8], label=None)
Inspect vectors:
[0 1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 9]


In [4]:
# Subtraction operation
print(c1 - c2)
print(c2 - c1)
print(c1 - x1)
print(c2 - x1)

[-1 -1 -1 -1 -1 -1 -1 -1 -1]
[1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1]
