In [1]:
# For testing aspects of kmeans
import numpy as np
from kmeans import Cluster

In [2]:
iris = np.loadtxt('data/iris-data.txt')
cancer = np.loadtxt('data/cancer-data.txt')

print(iris.shape)
print(cancer.shape)

(150, 5)
(105, 10)


In [4]:
sorted(np.random.choice(150, size=150, replace=False))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149]

In [11]:
# Deleting even items
lst = list(np.arange(0, 10))
print(lst)
for ix, item in enumerate(lst):
    if item % 2 == 0:
        print('DELETE:', item)
        # lst.remove(item)
        del lst[ix]

print(lst)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
DELETE: 0
DELETE: 2
DELETE: 4
DELETE: 6
DELETE: 8
[1, 3, 5, 7, 9]


In [2]:
samples = 10
features = 5
x = []
for i in range(samples):
    x.append(np.random.normal(size=(features, )))

centroid = np.mean(x, axis=0)
print(centroid.shape)

(5,)


In [6]:
x1 = np.arange(0, 9)
x2 = np.arange(1, 10)

c1 = Cluster(centroid=x1)
c2 = Cluster(centroid=x2)

print('Inspect Cluster:')
print(c1)

print('Check equality:')
print(c1 == c2)

print('Inspect vectors:')
print(x1)
print(x2)

Inspect Cluster:
<class 'kmeans.Cluster'> object at 0x29fec626dc0: (centroid=[0 1 2 3 4 5 6 7 8], label=None)
Check equality:
False
Inspect vectors:
[0 1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 9]


In [4]:
# Subtraction operation
print(c1 - c2)
print(c2 - c1)
print(c1 - x1)
print(c2 - x1)

[-1 -1 -1 -1 -1 -1 -1 -1 -1]
[1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1]
